apk add gettext-base for Python Dockerfile envsubst usage
GHA build of Python image may fail due to missing envsubst provided by gettext-base distro package. Let's install gettext-base for the build so avoiding the following error when the runner does not install that dependency automatically:
   Run #!/bin/bash
   /home/runner/_work/_temp/95e290b8-e4f0-4605-a1b7-4556cbcad1da.sh: line 3: envsubst: command not found
   Error: Process completed with exit code 127.